version: '2'

services:
  instatom:
    container_name: instatom
    build: .
    environment:
      - PORT=4032
    expose:
      - 4032
    ports:
    - "4032:4032"
  redis:
    image: redis:3.2-2.1.2
    ports:
      - '6379:6379'
